[project]
name = "my_fsr"
version = "2.5.0GH"

[build]
mode = "turbo"
target = "cpp"
output = "./gen_build"
incremental = true
parallel = true
cache = true
flags = ["--pack", "--pool"]

[aot]
enabled = true
runtimes = ["linux-x64", "win-x64", "osx-x64"]
trim = false
ready_to_run = true
single_file = true

[deps]
fmt = "11.0"