<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>BPlus.Cli</RootNamespace>
    <AssemblyName>bpc</AssemblyName>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BPlus.Core\BPlus.Core.csproj" />
    <ProjectReference Include="..\BPlus.Targets\BPlus.Targets.csproj" />
    <ProjectReference Include="..\BPlus.Runtime\BPlus.Runtime.csproj" />
  </ItemGroup>
</Project>
