const std = @import("std");
const Allocator = std.mem.Allocator;
const bir = @import("bir.zig");
const types = @import("bir_types.zig");
const bir_cfg = @import("bir_cfg.zig");

fn typeToHlsl(tid: types.TypeId, tt: *const types.TypeTable) []const u8 {
    const t = tt.get(tid);
    return switch (t.kind) {
        .void => "void",
        .scalar => |sk| switch (sk) {
            .i1 => "bool",
            .i8, .i16, .i32 => "int",
            .i64 => "int64_t",
            .u8, .u16, .u32 => "uint",
            .u64 => "uint64_t",
            .f16 => "min16float",
            .bf16 => "float",
            .f32 => "float",
            .f64 => "double",
        },
        .vector => |v| switch (v.scalar) {
            .f32 => switch (v.len) {
                2 => "float2",
                3 => "float3",
                4 => "float4",
                else => "float",
            },
            .u32 => switch (v.len) {
                2 => "uint2",
                3 => "uint3",
                4 => "uint4",
                else => "uint",
            },
            .i32 => switch (v.len) {
                2 => "int2",
                3 => "int3",
                4 => "int4",
                else => "int",
            },
            .f16 => switch (v.len) {
                2 => "min16float2",
                3 => "min16float3",
                4 => "min16float4",
                else => "min16float",
            },
            else => "float",
        },
        .pointer => "uint",
        .array => |a| blk: {
            const elem = typeToHlsl(a.elem, tt);
            break :blk elem;
        },
        .texture => |tk| switch (tk) {
            .tex2d => "Texture2D<float4>",
            .rw_tex2d => "RWTexture2D<float4>",
            .tex2d_array => "Texture2DArray<float4>",
            .tex3d => "Texture3D<float4>",
            .rw_tex3d => "RWTexture3D<float4>",
            else => "Texture2D<float4>",
        },
        .sampler => "SamplerState",
        .buffer => |bk| switch (bk) {
            .structured => "StructuredBuffer<float4>",
            .rw_structured => "RWStructuredBuffer<float4>",
            .raw => "ByteAddressBuffer",
            .rw_raw => "RWByteAddressBuffer",
            .typed => "Texture2D<float4>",
            .rw_typed => "RWTexture2D<float4>",
            .constant => "cbuffer",
        },
        else => "float",
    };
}

fn emitResourceDecl(w: anytype, res: *const bir.ResourceDecl, tt: *const types.TypeTable) !void {
    const tstr = typeToHlsl(res.ty, tt);
    const prefix = resourceRegisterPrefix(res.ty, tt);
    try w.print("{s} {s} : register({c}{d});\n", .{ tstr, res.name, prefix, res.binding });
}

fn resourceRegisterPrefix(tid: types.TypeId, tt: *const types.TypeTable) u8 {
    const t = tt.get(tid);
    return switch (t.kind) {
        .texture => |tk| switch (tk) {
            .rw_tex1d, .rw_tex2d, .rw_tex3d => 'u',
            else => 't',
        },
        .sampler => 's',
        .buffer => |bk| switch (bk) {
            .rw_structured, .rw_raw, .rw_typed => 'u',
            .constant => 'b',
            else => 't',
        },
        else => 't',
    };
}

pub fn generateHlsl(allocator: Allocator, module: *bir.Module) ![]const u8 {
    var buf = std.ArrayList(u8).init(allocator);
    const w = buf.writer();

    try w.writeAll("// Generated by BIR→HLSL\n");
    try w.writeAll("#include \"/Engine/Public/Platform.ush\"\n\n");

    for (module.resources.items) |res| {
        try emitResourceDecl(w, &res, &module.types);
    }
    try w.writeAll("\n");

    for (module.functions.items) |func| {
        try w.print("[numthreads({}, {}, {})]\n", .{ func.numthreads.x, func.numthreads.y, func.numthreads.z });
        try w.print("void {s}(uint3 __tid : SV_DispatchThreadID)\n", .{func.name});
        try w.writeAll("{\n");

        var var_names = std.AutoHashMap(bir.ValueId, []const u8).init(module.allocator);
        defer var_names.deinit();

        for (func.blocks.items) |block| {
            for (block.instrs.items) |inst| {
                if (inst.result == bir.NO_VALUE) continue;
                const vname = if (inst.op == .resource)
                    inst.data.string
                else
                    try std.fmt.allocPrint(module.allocator, "_v{d}", .{inst.result});
                try var_names.put(inst.result, vname);
                if (inst.op == .resource) continue;
                if (inst.op == .store) continue;
                const tstr = typeToHlsl(inst.ty, &module.types);
                if (!std.mem.eql(u8, tstr, "void")) {
                    try w.print("    {s} {s};\n", .{ tstr, vname });
                }
            }
        }

        var cfg = try bir_cfg.buildCFG(allocator, &func);
        defer cfg.deinit();

        for (cfg.rpo.items) |bid| {
            const block = &func.blocks.items[bid];
            for (block.instrs.items) |inst| {
                if (isTerminator(inst.op)) continue;
                try emitInst(w, &inst, &var_names, &module.types);
            }
        }

        try w.writeAll("    return;\n");
        try w.writeAll("}\n\n");
    }

    return buf.toOwnedSlice();
}

fn isTerminator(op: bir.Op) bool {
    return switch (op) {
        .br, .cond_br, .ret, .unreachable_op => true,
        else => false,
    };
}

fn emitInst(w: anytype, inst: *const bir.Inst, var_names: *const std.AutoHashMap(bir.ValueId, []const u8), tt: *const types.TypeTable) !void {
    const name = if (inst.result != bir.NO_VALUE) var_names.get(inst.result) else null;

    switch (inst.op) {
        .br, .cond_br, .ret, .unreachable_op => {},
        .phi => {
            if (name) |n| {
                switch (inst.data) {
                    .phi_incoming => |incoming| {
                        try w.print("    // phi: {s} = merge ", .{n});
                        for (incoming, 0..) |inc, pi| {
                            if (pi > 0) try w.writeAll(", ");
                            try w.print("%{d} from block_{d}", .{ inc.value, inc.block });
                        }
                        try w.writeAll("\n");
                    },
                    else => {},
                }
            }
        },
        .@"const" => {
            if (name) |n| {
                switch (inst.data) {
                    .const_data => |cd| {
                        switch (cd) {
                            .int => |v| try w.print("    {s} = {d};\n", .{ n, v }),
                            .float => |v| try w.print("    {s} = {d};\n", .{ n, v }),
                            .bool => |v| try w.print("    {s} = {};\n", .{ n, @as(i32, @intFromBool(v)) }),
                            else => try w.print("    {s} = 0;\n", .{n}),
                        }
                    },
                    else => try w.print("    {s} = 0;\n", .{n}),
                }
            }
        },
        .thread_id => {
            if (name) |n| {
                switch (inst.data) {
                    .group_info => |gi| {
                        const dims = [_][]const u8{ "x", "y", "z" };
                        try w.print("    {s} = __tid.{s};\n", .{ n, dims[@as(usize, @intCast(gi.dim))] });
                    },
                    else => try w.print("    {s} = __tid.x;\n", .{n}),
                }
            }
        },
        .add, .sub, .mul, .div, .mod,
        .fadd, .fsub, .fmul, .fdiv, .fmod,
        => {
            if (name) |n| {
                const op_sym = switch (inst.op) {
                    .add, .fadd => "+",
                    .sub, .fsub => "-",
                    .mul, .fmul => "*",
                    .div, .fdiv => "/",
                    .mod, .fmod => "%",
                    else => "?",
                };
                if (inst.operands.len >= 2) {
                    const lhs = var_names.get(inst.operands[0]) orelse "0";
                    const rhs = var_names.get(inst.operands[1]) orelse "0";
                    try w.print("    {s} = {s} {s} {s};\n", .{ n, lhs, op_sym, rhs });
                }
            }
        },
        .neg, .fneg => {
            if (name) |n| {
                if (inst.operands.len >= 1) {
                    const op = var_names.get(inst.operands[0]) orelse "0";
                    try w.print("    {s} = -({s});\n", .{ n, op });
                }
            }
        },
        .lt, .le, .gt, .ge, .eq, .ne,
        .flt, .fle, .fgt, .fge, .feq, .fne,
        => {
            if (name) |n| {
                const op_sym = switch (inst.op) {
                    .lt, .flt => "<",
                    .le, .fle => "<=",
                    .gt, .fgt => ">",
                    .ge, .fge => ">=",
                    .eq, .feq => "==",
                    .ne, .fne => "!=",
                    else => "?",
                };
                if (inst.operands.len >= 2) {
                    const lhs = var_names.get(inst.operands[0]) orelse "0";
                    const rhs = var_names.get(inst.operands[1]) orelse "0";
                    try w.print("    {s} = {s} {s} {s};\n", .{ n, lhs, op_sym, rhs });
                }
            }
        },
        .resource => {},
        .texture_sample => {
            if (name) |n| {
                switch (inst.data) {
                    .sample_info => |si| {
                        const tex = var_names.get(si.tex) orelse "?";
                        const samp = var_names.get(si.sampler) orelse "?";
                        const coord = var_names.get(si.coord) orelse "0";
                        if (si.lod) |lod_val| {
                            const lod = var_names.get(lod_val) orelse "0";
                            try w.print("    {s} = {s}.SampleLevel({s}, {s}, {s});\n", .{ n, tex, samp, coord, lod });
                        } else {
                            try w.print("    {s} = {s}.Sample({s}, {s});\n", .{ n, tex, samp, coord });
                        }
                    },
                    else => {},
                }
            }
        },
        .texture_load => {
            if (name) |n| {
                if (inst.operands.len >= 3) {
                    const tex = var_names.get(inst.operands[0]) orelse "?";
                    const coord_x = var_names.get(inst.operands[1]) orelse "0";
                    const coord_y = var_names.get(inst.operands[2]) orelse "0";
                    try w.print("    {s} = {s}.Load(uint3({s}, {s}, 0));\n", .{ n, tex, coord_x, coord_y });
                }
            }
        },
        .texture_store => {
            switch (inst.data) {
                .texture_store_info => |info| {
                    const tex = var_names.get(info.tex) orelse "?";
                    const coord_x = var_names.get(info.coord_x) orelse "0";
                    const coord_y = var_names.get(info.coord_y) orelse "0";
                    const val = var_names.get(info.val) orelse "0";
                    try w.print("    {s}[uint2({s}, {s})] = {s};\n", .{ tex, coord_x, coord_y, val });
                },
                else => {},
            }
        },
        .texture_query_dimensions => {
            if (name) |n| {
                if (inst.operands.len >= 1) {
                    const tex = var_names.get(inst.operands[0]) orelse "?";
                    try w.print("    {s}; {s}.GetDimensions({s}, {s});\n", .{ n, tex, n, n });
                }
            }
        },
        .load => {
            if (name) |n| {
                if (inst.operands.len >= 1) {
                    const ptr = var_names.get(inst.operands[0]) orelse "?";
                    try w.print("    {s} = {s};\n", .{ n, ptr });
                }
            }
        },
        .store => {
            if (inst.operands.len == 2) {
                const ptr = var_names.get(inst.operands[0]) orelse "?";
                const val = var_names.get(inst.operands[1]) orelse "0";
                try w.print("    {s} = {s};\n", .{ ptr, val });
            } else if (inst.operands.len >= 3) {
                const resource = var_names.get(inst.operands[0]) orelse "?";
                const index = var_names.get(inst.operands[1]) orelse "0";
                const val = var_names.get(inst.operands[2]) orelse "0";
                try w.print("    {s}[{s}] = {s};\n", .{ resource, index, val });
            }
        },
        .call => {
            if (name) |n| {
                switch (inst.data) {
                    .named_call => |nc| {
                        try emitNamedCall(w, n, nc, var_names);
                    },
                    .call_info => |ci| {
                        try w.print("    {s} = ", .{n});
                        const callee_name = var_names.get(ci.callee) orelse "?";
                        try w.print("fn_{s}(", .{callee_name});
                        for (ci.args, 0..) |arg, ai| {
                            if (ai > 0) try w.writeAll(", ");
                            const aname = var_names.get(arg) orelse "?";
                            try w.writeAll(aname);
                        }
                        try w.writeAll(");\n");
                    },
                    else => {},
                }
            } else {
                switch (inst.data) {
                    .named_call => |nc| {
                        try emitNamedCallNoResult(w, nc, var_names);
                    },
                    .call_info => |ci| {
                        const callee_name = var_names.get(ci.callee) orelse "?";
                        try w.print("fn_{s}(", .{callee_name});
                        for (ci.args, 0..) |arg, ai| {
                            if (ai > 0) try w.writeAll(", ");
                            const aname = var_names.get(arg) orelse "?";
                            try w.writeAll(aname);
                        }
                        try w.writeAll(");\n");
                    },
                    else => {},
                }
            }
        },
        .select => {
            if (name) |n| {
                if (inst.operands.len >= 3) {
                    const cond = var_names.get(inst.operands[0]) orelse "true";
                    const t_val = var_names.get(inst.operands[1]) orelse "0";
                    const f_val = var_names.get(inst.operands[2]) orelse "0";
                    try w.print("    {s} = {s} ? {s} : {s};\n", .{ n, cond, t_val, f_val });
                }
            }
        },
        .not => {
            if (name) |n| {
                const op = var_names.get(inst.operands[0]) orelse "0";
                try w.print("    {s} = !({s});\n", .{ n, op });
            }
        },
        .or_op, .and_op, .xor_op => {
            if (name) |n| {
                const op_sym = switch (inst.op) {
                    .or_op => "|",
                    .and_op => "&",
                    .xor_op => "^",
                    else => "?",
                };
                if (inst.operands.len >= 2) {
                    const lhs = var_names.get(inst.operands[0]) orelse "0";
                    const rhs = var_names.get(inst.operands[1]) orelse "0";
                    try w.print("    {s} = {s} {s} {s};\n", .{ n, lhs, op_sym, rhs });
                }
            }
        },
        .extract => {
            if (name) |n| {
                if (inst.operands.len >= 2) {
                    const base = var_names.get(inst.operands[0]) orelse "?";
                    const idx = var_names.get(inst.operands[1]) orelse "0";
                    try w.print("    {s} = {s}[{s}];\n", .{ n, base, idx });
                }
            }
        },
        .composite => {
            if (name) |n| {
                if (inst.operands.len >= 1) {
                    const tstr = typeToHlsl(inst.ty, tt);
                    try w.print("    {s} = {s}(", .{ n, tstr });
                    for (inst.operands, 0..) |op, oi| {
                        if (oi > 0) try w.writeAll(", ");
                        try w.writeAll(var_names.get(op) orelse "?");
                    }
                    try w.writeAll(");\n");
                }
            }
        },
        .cast => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                const tstr = typeToHlsl(inst.ty, tt);
                try w.print("    {s} = ({s})({s});\n", .{ n, tstr, op });
            }
        },
        .max, .min => {
            if (name) |n| {
                const is_max = inst.op == .max;
                if (inst.operands.len >= 2) {
                    const lhs = var_names.get(inst.operands[0]) orelse "0";
                    const rhs = var_names.get(inst.operands[1]) orelse "0";
                    const fname = if (is_max) "max" else "min";
                    try w.print("    {s} = {s}({s}, {s});\n", .{ n, fname, lhs, rhs });
                }
            }
        },
        .sqrt => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = sqrt({s});\n", .{ n, op });
            }
        },
        .rsqrt => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = rsqrt({s});\n", .{ n, op });
            }
        },
        .abs => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = abs({s});\n", .{ n, op });
            }
        },
        .floor => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = floor({s});\n", .{ n, op });
            }
        },
        .ceil => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = ceil({s});\n", .{ n, op });
            }
        },
        .frac => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = frac({s});\n", .{ n, op });
            }
        },
        .sin => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = sin({s});\n", .{ n, op });
            }
        },
        .cos => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = cos({s});\n", .{ n, op });
            }
        },
        .exp => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = exp({s});\n", .{ n, op });
            }
        },
        .log => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = log({s});\n", .{ n, op });
            }
        },
        .saturate => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = saturate({s});\n", .{ n, op });
            }
        },
        .lerp => {
            if (name) |n| {
                if (inst.operands.len >= 3) {
                    const a = var_names.get(inst.operands[0]) orelse "0";
                    const b = var_names.get(inst.operands[1]) orelse "0";
                    const t = var_names.get(inst.operands[2]) orelse "0";
                    try w.print("    {s} = lerp({s}, {s}, {s});\n", .{ n, a, b, t });
                }
            }
        },
        .fma => {
            if (name) |n| {
                if (inst.operands.len >= 3) {
                    const a = var_names.get(inst.operands[0]) orelse "0";
                    const b = var_names.get(inst.operands[1]) orelse "0";
                    const c = var_names.get(inst.operands[2]) orelse "0";
                    try w.print("    {s} = fma({s}, {s}, {s});\n", .{ n, a, b, c });
                }
            }
        },
        .vector_dot => {
            if (name) |n| {
                if (inst.operands.len >= 2) {
                    const a = var_names.get(inst.operands[0]) orelse "0";
                    const b = var_names.get(inst.operands[1]) orelse "0";
                    try w.print("    {s} = dot({s}, {s});\n", .{ n, a, b });
                }
            }
        },
        .barrier => {
            switch (inst.data) {
                .barrier_kind => |bk| {
                    const gname = switch (bk) {
                        .group => "GroupMemoryBarrierWithGroupSync",
                        .device => "DeviceMemoryBarrierWithGroupSync",
                        .all => "AllMemoryBarrierWithGroupSync",
                    };
                    try w.print("    {s}();\n", .{gname});
                },
                else => try w.writeAll("    GroupMemoryBarrierWithGroupSync();\n"),
            }
        },
        .groupshared_barrier => {
            try w.writeAll("    GroupMemoryBarrierWithGroupSync();\n");
        },
        .wave_get_lane_index => {
            if (name) |n| try w.print("    {s} = WaveGetLaneIndex();\n", .{n});
        },
        .wave_is_first_lane => {
            if (name) |n| try w.print("    {s} = WaveIsFirstLane();\n", .{n});
        },
        .wave_read_lane_first => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = WaveReadLaneFirst({s});\n", .{ n, op });
            }
        },
        .wave_active_all_equal => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = WaveActiveAllEqual({s});\n", .{ n, op });
            }
        },
        .quad_read_across_x => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = QuadReadAcrossX({s});\n", .{ n, op });
            }
        },
        .quad_read_across_y => {
            if (name) |n| {
                const op = if (inst.operands.len >= 1) var_names.get(inst.operands[0]) orelse "0" else "0";
                try w.print("    {s} = QuadReadAcrossY({s});\n", .{ n, op });
            }
        },
        else => {
            if (name) |n| {
                try w.print("    // {s} = {s} (unhandled)\n", .{ n, @tagName(inst.op) });
            } else {
                try w.print("    // {s} (unhandled)\n", .{@tagName(inst.op)});
            }
        },
    }
}

fn emitNamedCall(w: anytype, name: []const u8, nc: anytype, var_names: *const std.AutoHashMap(bir.ValueId, []const u8)) !void {
    const callee = nc.name;
    if (std.mem.eql(u8, callee, "@array_get")) {
        try w.print("    {s} = {s}[{s}]", .{ name, var_names.get(nc.args[0]) orelse "?", var_names.get(nc.args[1]) orelse "0" });
    } else if (std.mem.eql(u8, callee, "SampleLevel")) {
        const tex = var_names.get(nc.args[0]) orelse "?";
        const samp = var_names.get(nc.args[1]) orelse "?";
        const coord = var_names.get(nc.args[2]) orelse "0";
        const lod = if (nc.args.len > 3) var_names.get(nc.args[3]) orelse "0" else "0";
        try w.print("    {s} = {s}.SampleLevel({s}, {s}, {s})", .{ name, tex, samp, coord, lod });
    } else if (std.mem.eql(u8, callee, "Sample")) {
        const tex = var_names.get(nc.args[0]) orelse "?";
        const samp = var_names.get(nc.args[1]) orelse "?";
        const coord = var_names.get(nc.args[2]) orelse "0";
        try w.print("    {s} = {s}.Sample({s}, {s})", .{ name, tex, samp, coord });
    } else if (std.mem.eql(u8, callee, "Load")) {
        const tex = var_names.get(nc.args[0]) orelse "?";
        if (nc.args.len >= 3) {
            const cx = var_names.get(nc.args[1]) orelse "0";
            const cy = var_names.get(nc.args[2]) orelse "0";
            try w.print("    {s} = {s}.Load(uint3({s}, {s}, 0))", .{ name, tex, cx, cy });
        } else {
            const coord = var_names.get(nc.args[1]) orelse "0";
            try w.print("    {s} = {s}.Load({s})", .{ name, tex, coord });
        }
    } else if (std.mem.eql(u8, callee, "GetDimensions")) {
        const tex = var_names.get(nc.args[0]) orelse "?";
        if (nc.args.len >= 3) {
            const out_w = var_names.get(nc.args[1]) orelse "?";
            const out_h = var_names.get(nc.args[2]) orelse "?";
            try w.print("    {s}.GetDimensions({s}, {s})", .{ tex, out_w, out_h });
        } else {
            try w.print("    {s}.GetDimensions()", .{tex});
        }
    } else if (std.mem.startsWith(u8, callee, "Gather")) {
        const tex = var_names.get(nc.args[0]) orelse "?";
        const samp = var_names.get(nc.args[1]) orelse "?";
        const coord = if (nc.args.len > 2) var_names.get(nc.args[2]) orelse "0" else "0";
        try w.print("    {s} = {s}.{s}({s}, {s})", .{ name, tex, callee, samp, coord });
    } else {
        try w.print("    {s} = {s}(", .{ name, callee });
        for (nc.args, 0..) |arg, ai| {
            if (ai > 0) try w.writeAll(", ");
            try w.writeAll(var_names.get(arg) orelse "?");
        }
        try w.writeAll(")");
    }
    try w.writeAll(";\n");
}

fn emitNamedCallNoResult(w: anytype, nc: anytype, var_names: *const std.AutoHashMap(bir.ValueId, []const u8)) !void {
    const callee = nc.name;
    if (std.mem.eql(u8, callee, "GetDimensions")) {
        const tex = var_names.get(nc.args[0]) orelse "?";
        if (nc.args.len >= 3) {
            const out_w = var_names.get(nc.args[1]) orelse "?";
            const out_h = var_names.get(nc.args[2]) orelse "?";
            try w.print("    {s}.GetDimensions({s}, {s})", .{ tex, out_w, out_h });
        } else {
            try w.print("    {s}.GetDimensions()", .{tex});
        }
        try w.writeAll(";\n");
    }
}
