using System.Text;
using BPlus.Core.Ast;

namespace BPlus.Runtime;

public enum CpuArch { Unknown, X64_SSE2, X64_AVX, X64_AVX2, X64_AVX512, Arm64_NEON }

public record CpuCapability(string Name, CpuArch Arch, string FeatureFlag, double EstimatedIpc);

public static class CpuDetector
{
    private static readonly CpuCapability[] AllCaps =
    {
        new("SSE2", CpuArch.X64_SSE2, "sse2", 1.5),
        new("AVX", CpuArch.X64_AVX, "avx", 2.0),
        new("AVX2", CpuArch.X64_AVX2, "avx2", 2.5),
        new("AVX-512", CpuArch.X64_AVX512, "avx512f", 4.0),
        new("NEON", CpuArch.Arm64_NEON, "neon", 2.5),
    };

    public static CpuCapability DetectBest()
    {
        try
        {
            if (IsAvx512Supported()) return AllCaps[3];
            if (IsAvx2Supported()) return AllCaps[2];
            if (IsAvxSupported()) return AllCaps[1];
        }
        catch { }
        return AllCaps[0];
    }

    static bool IsAvx512Supported()
    {
        try
        {
            if (!OperatingSystem.IsWindows()) return false;
            var psi = new System.Diagnostics.ProcessStartInfo("wmic", "cpu get features") { RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true };
            using var p = System.Diagnostics.Process.Start(psi);
            var output = p?.StandardOutput.ReadToEnd();
            p?.WaitForExit(1000);
            return output?.Contains("AVX512F", StringComparison.OrdinalIgnoreCase) == true;
        }
        catch { return false; }
    }

    static bool IsAvx2Supported()
    {
        try
        {
            if (!OperatingSystem.IsWindows()) return false;
            var psi = new System.Diagnostics.ProcessStartInfo("wmic", "cpu get features") { RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true };
            using var p = System.Diagnostics.Process.Start(psi);
            var output = p?.StandardOutput.ReadToEnd();
            p?.WaitForExit(1000);
            return output?.Contains("AVX2", StringComparison.OrdinalIgnoreCase) == true;
        }
        catch { return false; }
    }

    static bool IsAvxSupported()
    {
        try
        {
            if (!OperatingSystem.IsWindows()) return false;
            var psi = new System.Diagnostics.ProcessStartInfo("wmic", "cpu get features") { RedirectStandardOutput = true, UseShellExecute = false, CreateNoWindow = true };
            using var p = System.Diagnostics.Process.Start(psi);
            var output = p?.StandardOutput.ReadToEnd();
            p?.WaitForExit(1000);
            return output?.Contains("AVX", StringComparison.OrdinalIgnoreCase) == true;
        }
        catch { return false; }
    }

    public static string GenerateCpuDetectionHeader()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by B+ Adaptive Runtime — CPU detection");
        sb.AppendLine("#ifndef BPLUS_ADAPTIVE_H");
        sb.AppendLine("#define BPLUS_ADAPTIVE_H");
        sb.AppendLine();
        sb.AppendLine("#include <cstdint>");
        sb.AppendLine("#include <cstring>");
        sb.AppendLine();
        sb.AppendLine("#ifdef _MSC_VER");
        sb.AppendLine("#include <intrin.h>");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine("enum CpuArch : uint8_t {");
        sb.AppendLine("    CPU_UNKNOWN = 0,");
        sb.AppendLine("    CPU_SSE2    = 1,");
        sb.AppendLine("    CPU_AVX     = 2,");
        sb.AppendLine("    CPU_AVX2    = 3,");
        sb.AppendLine("    CPU_AVX512  = 4,");
        sb.AppendLine("    CPU_NEON    = 5,");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("struct CpuCapabilities {");
        sb.AppendLine("    CpuArch arch;");
        sb.AppendLine("    bool hasFMA;");
        sb.AppendLine("    bool hasBMI2;");
        sb.AppendLine("    uint32_t simdWidth;  // 128/256/512");
        sb.AppendLine("    uint32_t cacheLineSize;");
        sb.AppendLine("    uint32_t l1CacheKB;");
        sb.AppendLine("    uint32_t l2CacheKB;");
        sb.AppendLine("    uint32_t l3CacheKB;");
        sb.AppendLine("    int32_t  numaNodes;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("inline void cpuid(int32_t info[4], int32_t leaf) {");
        sb.AppendLine("#ifdef _MSC_VER");
        sb.AppendLine("    __cpuidex(info, leaf, 0);");
        sb.AppendLine("#elif defined(__GNUC__) || defined(__clang__)");
        sb.AppendLine("    __asm__ volatile(\"cpuid\" : \"=a\"(info[0]), \"=b\"(info[1]), \"=c\"(info[2]), \"=d\"(info[3]) : \"a\"(leaf), \"c\"(0));");
        sb.AppendLine("#endif");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("inline CpuCapabilities detectCPU() {");
        sb.AppendLine("    CpuCapabilities cap = {};");
        sb.AppendLine("    int32_t info[4] = {};");
        sb.AppendLine("    cpuid(info, 0);");
        sb.AppendLine("    uint32_t maxLeaf = (uint32_t)info[0];");
        sb.AppendLine("    if (maxLeaf >= 1) {");
        sb.AppendLine("        cpuid(info, 1);");
        sb.AppendLine("        bool sse2  = (info[3] >> 26) & 1;");
        sb.AppendLine("        bool avx   = (info[2] >> 28) & 1;");
        sb.AppendLine("        bool fma   = (info[2] >> 12) & 1;");
        sb.AppendLine("        cap.hasFMA = fma;");
        sb.AppendLine("        if (maxLeaf >= 7) {");
        sb.AppendLine("            cpuid(info, 7);");
        sb.AppendLine("            bool avx2   = (info[1] >> 5) & 1;");
        sb.AppendLine("            bool avx512 = (info[1] >> 16) & 1;");
        sb.AppendLine("            cap.hasBMI2 = (info[1] >> 8) & 1;");
        sb.AppendLine("            if (avx512) { cap.arch = CPU_AVX512; cap.simdWidth = 512; }");
        sb.AppendLine("            else if (avx2) { cap.arch = CPU_AVX2; cap.simdWidth = 256; }");
        sb.AppendLine("            else if (avx)  { cap.arch = CPU_AVX; cap.simdWidth = 256; }");
        sb.AppendLine("            else if (sse2) { cap.arch = CPU_SSE2; cap.simdWidth = 128; }");
        sb.AppendLine("        } else {");
        sb.AppendLine("            cap.arch = sse2 ? CPU_SSE2 : CPU_UNKNOWN;");
        sb.AppendLine("            cap.simdWidth = 128;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("    cap.cacheLineSize = 64;");
        sb.AppendLine("    if (maxLeaf >= 4) {");
        sb.AppendLine("        cpuid(info, 4);");
        sb.AppendLine("        cap.l1CacheKB = ((info[1] >> 14) & 0xFFF) * 1024;");
        sb.AppendLine("    }");
        sb.AppendLine("    return cap;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Per-kernel dispatch table — populated at startup by benchmark");
        sb.AppendLine("struct KernelDispatch {");
        sb.AppendLine("    const char* name;");
        sb.AppendLine("    void (*fn_scalar)(void*);");
        sb.AppendLine("    void (*fn_sse2)(void*);");
        sb.AppendLine("    void (*fn_avx)(void*);");
        sb.AppendLine("    void (*fn_avx2)(void*);");
        sb.AppendLine("    void (*fn_avx512)(void*);");
        sb.AppendLine("    void (*fn_neon)(void*);");
        sb.AppendLine("    CpuArch bestArch;");
        sb.AppendLine("    double bestTimeMs;");
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("// Benchmark a kernel dispatch entry — runs all paths, picks fastest");
        sb.AppendLine("inline void benchmarkKernel(KernelDispatch* kd, void* ctx, int warmup, int runs) {");
        sb.AppendLine("    (void)ctx;");
        sb.AppendLine("    struct Times { CpuArch arch; double ms; } times[6];");
        sb.AppendLine("    int n = 0;");
        sb.AppendLine("    auto bench = [&](CpuArch arch, void (*fn)(void*)) {");
        sb.AppendLine("        if (!fn) return;");
        sb.AppendLine("        for (int i = 0; i < warmup; i++) fn(ctx);");
        sb.AppendLine("        auto t0 = __rdtsc();");
        sb.AppendLine("        for (int i = 0; i < runs; i++) fn(ctx);");
        sb.AppendLine("        auto t1 = __rdtsc();");
        sb.AppendLine("        times[n++] = {arch, (double)(t1 - t0) / runs};");
        sb.AppendLine("    };");
        sb.AppendLine("    bench(CPU_AVX512, kd->fn_avx512);");
        sb.AppendLine("    bench(CPU_AVX2,   kd->fn_avx2);");
        sb.AppendLine("    bench(CPU_AVX,    kd->fn_avx);");
        sb.AppendLine("    bench(CPU_SSE2,   kd->fn_sse2);");
        sb.AppendLine("    bench(CPU_NEON,   kd->fn_neon);");
        sb.AppendLine("    bench(CPU_UNKNOWN, kd->fn_scalar);");
        sb.AppendLine("    kd->bestTimeMs = 1e30;");
        sb.AppendLine("    for (int i = 0; i < n; i++) {");
        sb.AppendLine("        if (times[i].ms < kd->bestTimeMs) {");
        sb.AppendLine("            kd->bestTimeMs = times[i].ms;");
        sb.AppendLine("            kd->bestArch = times[i].arch;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("// Runtime dispatcher — calls the best implementation");
        sb.AppendLine("inline void dispatchKernel(KernelDispatch* kd, void* ctx) {");
        sb.AppendLine("    switch (kd->bestArch) {");
        sb.AppendLine("        case CPU_AVX512: if (kd->fn_avx512) { kd->fn_avx512(ctx); return; }");
        sb.AppendLine("        case CPU_AVX2:   if (kd->fn_avx2)   { kd->fn_avx2(ctx);   return; }");
        sb.AppendLine("        case CPU_AVX:    if (kd->fn_avx)    { kd->fn_avx(ctx);    return; }");
        sb.AppendLine("        case CPU_SSE2:   if (kd->fn_sse2)   { kd->fn_sse2(ctx);   return; }");
        sb.AppendLine("        case CPU_NEON:   if (kd->fn_neon)   { kd->fn_neon(ctx);   return; }");
        sb.AppendLine("        default:         if (kd->fn_scalar) { kd->fn_scalar(ctx); return; }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("#endif // BPLUS_ADAPTIVE_H");
        return sb.ToString();
    }

    public static string GenerateStateMachineDispatch(List<StateDefNode> states, List<string> events,
        Dictionary<string, int> stateIds, Dictionary<string, int> eventIds)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// Auto-generated by B+ Adaptive Runtime — state machine dispatch");
        sb.AppendLine("#include \"bplus_adaptive.h\"");
        sb.AppendLine();

        foreach (var st in states)
        {
            sb.AppendLine($"// State: {st.Name}");
            sb.AppendLine($"void state_{st.Name}_dispatch(void* ctx);");
        }
        sb.AppendLine();

        sb.AppendLine("// Startup: detect CPU + benchmark all states");
        sb.AppendLine("void bplus_adaptive_init() {");
        sb.AppendLine("    CpuCapabilities cap = detectCPU();");
        sb.AppendLine("    (void)cap;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("// Transition dispatch with CPU-adaptive path selection");
        sb.AppendLine("void bplus_dispatch(int stateId, int eventId, void* ctx) {");
        sb.AppendLine("    static const void* jumpTable[2][256] = {};");
        sb.AppendLine("    (void)stateId; (void)eventId; (void)ctx;");
        sb.AppendLine("    switch (stateId) {");
        foreach (var st in states)
        {
            int sid = stateIds[st.Name];
            sb.AppendLine($"        case {sid}: state_{st.Name}_dispatch(ctx); break;");
        }
        sb.AppendLine("        default: break;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

public static class AdaptiveRuntime
{
    public static string GenerateAdaptiveHeader(ProgramNode program)
    {
        return CpuDetector.GenerateCpuDetectionHeader();
    }

    public static string GenerateAdaptiveImpl(ProgramNode program,
        List<StateDefNode> states, List<string> events,
        Dictionary<string, int> stateIds, Dictionary<string, int> eventIds)
    {
        return CpuDetector.GenerateStateMachineDispatch(states, events, stateIds, eventIds);
    }

    public static string GenerateBenchmarkReport(List<StateDefNode> states)
    {
        var sb = new StringBuilder();
        sb.AppendLine("=== B+ Adaptive Runtime — Benchmark Report ===");
        sb.AppendLine($"Detected CPU: {CpuDetector.DetectBest().Name}");
        sb.AppendLine($"States: {states.Count}");
        sb.AppendLine();
        sb.AppendLine("Kernel Dispatch Table:");
        foreach (var st in states)
        {
            sb.AppendLine($"  {st.Name}: best path = auto-detect at startup");
        }
        return sb.ToString();
    }
}
