pub const TokenKind = enum(u16) {
    // Special
    eof = 0,
    error_token,

    // Literals
    int_literal,
    float_literal,
    string_literal,
    char_literal,
    byte_literal,
    byte_string_literal,
    true_literal,
    false_literal,
    null_literal,

    // Identifiers
    identifier,
    underscore,

    // Keywords
    kw_fn,
    kw_let,
    kw_var,
    kw_const,
    kw_mut,
    kw_return,
    kw_if,
    kw_else,
    kw_while,
    kw_for,
    kw_in,
    kw_loop,
    kw_break,
    kw_continue,
    kw_match,
    kw_struct,
    kw_enum,
    kw_trait,
    kw_impl,
    kw_type,
    kw_import,
    kw_export,
    kw_from,
    kw_as,
    kw_pub,
    kw_priv,
    kw_static,
    kw_extern,
    kw_self,
    kw_this,
    kw_super,
    kw_true,
    kw_false,
    kw_null,
    kw_void,
    kw_bool,
    kw_i8,
    kw_i16,
    kw_i32,
    kw_i64,
    kw_u8,
    kw_u16,
    kw_u32,
    kw_u64,
    kw_f32,
    kw_f64,
    kw_string,
    kw_any,
    kw_comptime,
    kw_inline,
    kw_noinline,
    kw_unreachable,
    kw_panic,
    kw_sizeof,
    kw_alignof,
    kw_typeof,
    kw_ref,
    kw_deref,
    kw_defer,
    kw_errdefer,
    kw_orelse,
    kw_catch,
    kw_try,
    kw_and,
    kw_or,
    kw_not,
    kw_async,
    kw_await,
    kw_yield,
    kw_atomic,
    kw_volatile,

    // Declarations
    kw_state,
    kw_entry,
    kw_kernel,
    kw_pipeline,
    kw_parallel,
    kw_forward,
    kw_use,

    // Transitions
    kw_on,
    kw_always,
    kw_fire,
    kw_machine,

    // Runtime
    kw_run,
    kw_print,
    kw_free,
    kw_body,
    kw_step,
    kw_publish,
    kw_enter,
    kw_exit,

    // Ownership
    kw_owned,
    kw_borrowed,

    // FFI
    kw_metal,
    kw_cxx,

    // Delimiters
    lparen,
    rparen,
    lbrace,
    rbrace,
    lbracket,
    rbracket,
    langlear,
    langle,
    rangle,
    rangleq,

    // Punctuation
    comma,
    semicolon,
    colon,
    colon_colon,
    dot,
    dot_dot,
    dot_dot_dot,
    dot_dot_eq,
    arrow,
    fat_arrow,
    at,
    hash,
    dollar,
    underscore_tok,
    question,
    excl_mark,

    // Operators
    plus,
    minus,
    star,
    slash,
    percent,
    caret,
    amp,
    pipe,
    tilde,
    bang,
    eq,
    eq_eq,
    bang_eq,
    less,
    greater,
    less_eq,
    greater_eq,
    plus_eq,
    minus_eq,
    star_eq,
    slash_eq,
    percent_eq,
    caret_eq,
    amp_eq,
    pipe_eq,
    shl,
    shr,
    shl_eq,
    shr_eq,
    amp_amp,
    pipe_pipe,
    plus_plus,

    // Whitespace
    newline,
    whitespace,
    tab,

    // Comments
    line_comment,
    block_comment,

    // Doc comments
    doc_comment_single,
    doc_comment_multi,

    pub fn isKeyword(self: TokenKind) bool {
        return switch (self) {
            .kw_fn, .kw_let, .kw_var, .kw_const, .kw_mut,
            .kw_return, .kw_if, .kw_else, .kw_while, .kw_for,
            .kw_in, .kw_loop, .kw_break, .kw_continue, .kw_match,
            .kw_struct, .kw_enum, .kw_trait, .kw_impl, .kw_type,
            .kw_import, .kw_export, .kw_from, .kw_as,
            .kw_pub, .kw_priv, .kw_static, .kw_extern,
            .kw_self, .kw_this, .kw_super,
            .kw_true, .kw_false, .kw_null,
            .kw_void, .kw_bool,
            .kw_i8, .kw_i16, .kw_i32, .kw_i64,
            .kw_u8, .kw_u16, .kw_u32, .kw_u64,
            .kw_f32, .kw_f64, .kw_string, .kw_any,
            .kw_comptime, .kw_inline, .kw_noinline,
            .kw_unreachable, .kw_panic,
            .kw_sizeof, .kw_alignof, .kw_typeof,
            .kw_ref, .kw_deref,
            .kw_defer, .kw_errdefer,
            .kw_orelse, .kw_catch, .kw_try,
            .kw_and, .kw_or, .kw_not,
            .kw_async, .kw_await, .kw_yield,
            .kw_atomic, .kw_volatile,
            .kw_state, .kw_entry, .kw_on, .kw_always, .kw_parallel,
            .kw_kernel, .kw_pipeline, .kw_forward,
            .kw_run, .kw_print, .kw_free, .kw_body, .kw_step,
            .kw_publish, .kw_enter, .kw_exit,
            .kw_owned, .kw_borrowed,
            .kw_use, .kw_metal, .kw_cxx,
            => true,
            else => false,
        };
    }

    pub fn isLiteral(self: TokenKind) bool {
        return @intFromEnum(self) >= @intFromEnum(TokenKind.int_literal) and
            @intFromEnum(self) <= @intFromEnum(TokenKind.null_literal);
    }

    pub fn isOperator(self: TokenKind) bool {
        return @intFromEnum(self) >= @intFromEnum(TokenKind.plus) and
            @intFromEnum(self) <= @intFromEnum(TokenKind.plus_plus);
    }

    pub fn isDelimiter(self: TokenKind) bool {
        return @intFromEnum(self) >= @intFromEnum(TokenKind.lparen) and
            @intFromEnum(self) <= @intFromEnum(TokenKind.excl_mark);
    }

    pub fn isTrivia(self: TokenKind) bool {
        return self == .whitespace or self == .newline or self == .tab or
            self == .line_comment or self == .block_comment or
            self == .doc_comment_single or self == .doc_comment_multi;
    }

    pub fn isOpenDelimiter(self: TokenKind) bool {
        return switch (self) {
            .lparen, .lbrace, .lbracket, .langle => true,
            else => false,
        };
    }

    pub fn isCloseDelimiter(self: TokenKind) bool {
        return switch (self) {
            .rparen, .rbrace, .rbracket, .rangle => true,
            else => false,
        };
    }

    pub fn matchingClose(self: TokenKind) ?TokenKind {
        return switch (self) {
            .lparen => .rparen,
            .lbrace => .rbrace,
            .lbracket => .rbracket,
            .langle => .rangle,
            else => null,
        };
    }

    pub fn spelling(self: TokenKind) []const u8 {
        return self.name();
    }

    pub fn name(self: TokenKind) []const u8 {
        return switch (self) {
            .eof => "EOF",
            .error_token => "error",
            .int_literal => "integer literal",
            .float_literal => "float literal",
            .string_literal => "string literal",
            .char_literal => "char literal",
            .byte_literal => "byte literal",
            .byte_string_literal => "byte string literal",
            .true_literal => "true",
            .false_literal => "false",
            .null_literal => "null",
            .identifier => "identifier",
            .underscore => "_",
            .kw_fn => "fn",
            .kw_let => "let",
            .kw_var => "var",
            .kw_const => "const",
            .kw_mut => "mut",
            .kw_return => "return",
            .kw_if => "if",
            .kw_else => "else",
            .kw_while => "while",
            .kw_for => "for",
            .kw_in => "in",
            .kw_loop => "loop",
            .kw_break => "break",
            .kw_continue => "continue",
            .kw_match => "match",
            .kw_struct => "struct",
            .kw_enum => "enum",
            .kw_trait => "trait",
            .kw_impl => "impl",
            .kw_type => "type",
            .kw_import => "import",
            .kw_export => "export",
            .kw_from => "from",
            .kw_as => "as",
            .kw_pub => "pub",
            .kw_priv => "priv",
            .kw_static => "static",
            .kw_extern => "extern",
            .kw_self => "self",
            .kw_this => "this",
            .kw_super => "super",
            .kw_true => "true",
            .kw_false => "false",
            .kw_null => "null",
            .kw_void => "void",
            .kw_bool => "bool",
            .kw_i8 => "i8",
            .kw_i16 => "i16",
            .kw_i32 => "i32",
            .kw_i64 => "i64",
            .kw_u8 => "u8",
            .kw_u16 => "u16",
            .kw_u32 => "u32",
            .kw_u64 => "u64",
            .kw_f32 => "f32",
            .kw_f64 => "f64",
            .kw_string => "string",
            .kw_any => "any",
            .kw_comptime => "comptime",
            .kw_inline => "inline",
            .kw_noinline => "noinline",
            .kw_unreachable => "unreachable",
            .kw_panic => "panic",
            .kw_sizeof => "sizeof",
            .kw_alignof => "alignof",
            .kw_typeof => "typeof",
            .kw_ref => "ref",
            .kw_deref => "deref",
            .kw_defer => "defer",
            .kw_errdefer => "errdefer",
            .kw_orelse => "orelse",
            .kw_catch => "catch",
            .kw_try => "try",
            .kw_and => "and",
            .kw_or => "or",
            .kw_not => "not",
            .kw_async => "async",
            .kw_await => "await",
            .kw_yield => "yield",
            .kw_atomic => "atomic",
            .kw_volatile => "volatile",
            .kw_state => "state",
            .kw_entry => "entry",
            .kw_on => "on",
            .kw_always => "always",
            .kw_parallel => "parallel",
            .kw_kernel => "kernel",
            .kw_pipeline => "pipeline",
            .kw_forward => "forward",
            .kw_run => "run",
            .kw_print => "print",
            .kw_free => "free",
            .kw_body => "body",
            .kw_step => "step",
            .kw_publish => "publish",
            .kw_enter => "enter",
            .kw_exit => "exit",
            .kw_owned => "owned",
            .kw_borrowed => "borrowed",
            .kw_use => "use",
            .kw_metal => "metal",
            .kw_cxx => "cxx",
            .lparen => "(",
            .rparen => ")",
            .lbrace => "{",
            .rbrace => "}",
            .lbracket => "[",
            .rbracket => "]",
            .langlear => "<<",
            .langle => "<",
            .rangle => ">",
            .rangleq => ">=",
            .comma => ",",
            .semicolon => ";",
            .colon => ":",
            .colon_colon => "::",
            .dot => ".",
            .dot_dot => "..",
            .dot_dot_dot => "...",
            .dot_dot_eq => "..=",
            .arrow => "->",
            .fat_arrow => "=>",
            .at => "@",
            .hash => "#",
            .dollar => "$",
            .underscore_tok => "_",
            .question => "?",
            .excl_mark => "!",
            .plus => "+",
            .minus => "-",
            .star => "*",
            .slash => "/",
            .percent => "%",
            .caret => "^",
            .amp => "&",
            .pipe => "|",
            .tilde => "~",
            .bang => "!",
            .eq => "=",
            .eq_eq => "==",
            .bang_eq => "!=",
            .less => "<",
            .greater => ">",
            .less_eq => "<=",
            .greater_eq => ">=",
            .plus_eq => "+=",
            .minus_eq => "-=",
            .star_eq => "*=",
            .slash_eq => "/=",
            .percent_eq => "%=",
            .caret_eq => "^=",
            .amp_eq => "&=",
            .pipe_eq => "|=",
            .shl => "<<",
            .shr => ">>",
            .shl_eq => "<<=",
            .shr_eq => ">>=",
            .amp_amp => "&&",
            .pipe_pipe => "||",
            .plus_plus => "++",
            .newline => "\\n",
            .whitespace => " ",
            .tab => "\\t",
            .line_comment => "//...",
            .block_comment => "/*...*/",
            .doc_comment_single => "///...",
            .doc_comment_multi => "/**...*/",
        };
    }
};
