<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>BPlus.Debugger</RootNamespace>
    <AssemblyName>BPlus.Debugger</AssemblyName>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BPlus.Core\BPlus.Core.csproj" />
    <ProjectReference Include="..\BPlus.Targets\BPlus.Targets.csproj" />
  </ItemGroup>
</Project>
