const std = @import("std");
const ast = @import("ast.zig");

pub const Generator = struct {
    allocator: std.mem.Allocator,
    buf: std.ArrayList(u8),
    strings: std.ArrayList([]const u8) = undefined,
    prog: *const ast.Program = undefined,
    context_fields: usize = 0,
    tmp_counter: usize = 0,

    pub fn init(allocator: std.mem.Allocator) Generator {
        return .{ .allocator = allocator, .buf = std.ArrayList(u8).init(allocator) };
    }

    pub fn generate(g: *Generator, prog: ast.Program) ![]const u8 {
        g.prog = &prog;
        g.context_fields = g.countContextFields(prog);
        g.strings = std.ArrayList([]const u8).init(g.allocator);
        g.tmp_counter = 0;

        try g.write("; Generated by B+ Zig Backend (LLVM IR)\n");
        try g.write("target datalayout = \"e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"\n\n");
        try g.write("declare i32 @puts(ptr)\n");
        try g.write("declare void @bplus_write(ptr, i32)\n");
        try g.write("declare void @bplus_print_i32(i32)\n");
        try g.write("declare void @llvm.prefetch(ptr, i32, i32, i32)\n");
        try g.write("declare i64 @llvm.expect.i64(i64, i64)\n\n");

        try g.collectStrings(prog);
        try g.emitStringConstants();
        try g.emitContextType(prog);

        for (prog.states.items) |st| {
            try g.genStateFn(st);
            try g.write("\n");
        }

        try g.genMain(prog);
        return g.buf.items;
    }

    fn nextTmp(g: *Generator) ![]const u8 {
        const reg = try std.fmt.allocPrint(g.allocator, "%v{d}", .{g.tmp_counter});
        g.tmp_counter += 1;
        return reg;
    }

    fn findContextFieldIdx(g: *Generator, name: []const u8) !usize {
        for (g.prog.context_vars.items, 0..) |v, i| {
            if (std.mem.eql(u8, v.name, name)) return i;
        }
        var idx = g.prog.context_vars.items.len;
        for (g.prog.states.items) |st| {
            for (st.vars.items) |sv| {
                if (std.mem.eql(u8, sv.name, name)) return idx;
                idx += 1;
            }
        }
        return error.VariableNotFound;
    }

    fn icmpCond(op: []const u8) []const u8 {
        if (std.mem.eql(u8, op, ">")) return "sgt";
        if (std.mem.eql(u8, op, "<")) return "slt";
        if (std.mem.eql(u8, op, ">=")) return "sge";
        if (std.mem.eql(u8, op, "<=")) return "sle";
        if (std.mem.eql(u8, op, "==")) return "eq";
        if (std.mem.eql(u8, op, "!=")) return "ne";
        return "eq";
    }

    /// Generates LLVM IR for an expression, returning its value text (SSA register or constant).
    /// Caller must free the returned slice.
    fn genLlvmExpr(g: *Generator, expr: *ast.Expr) ![]const u8 {
        switch (expr.kind) {
            .literal => {
                switch (expr.literal.lit_type) {
                    .int => return try std.fmt.allocPrint(g.allocator, "{d}", .{expr.literal.int_val}),
                    .float => return try std.fmt.allocPrint(g.allocator, "{d}", .{expr.literal.float_val}),
                    .boolean => return try std.fmt.allocPrint(g.allocator, "{d}", .{@intFromBool(expr.literal.bool_val)}),
                    .string => return try g.allocator.dupe(u8, "0"),
                }
            },
            .ident => {
                const idx = try g.findContextFieldIdx(expr.ident);
                const ptr_reg = try g.nextTmp();
                const val_reg = try g.nextTmp();
                try g.write("  ");
                try g.write(ptr_reg);
                try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
                try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                try g.write("\n");
                try g.write("  ");
                try g.write(val_reg);
                try g.write(" = load i32, ptr ");
                try g.write(ptr_reg);
                try g.write("\n");
                g.allocator.free(ptr_reg);
                return val_reg;
            },
            .binary => {
                const left_val = try g.genLlvmExpr(expr.left.?);
                errdefer g.allocator.free(left_val);
                const right_val = try g.genLlvmExpr(expr.right.?);
                errdefer g.allocator.free(right_val);

                const result = try g.nextTmp();
                if (std.mem.eql(u8, expr.op, "&&")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = and i1 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                } else if (std.mem.eql(u8, expr.op, "||")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = or i1 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                } else if (std.mem.eql(u8, expr.op, "+")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = add i32 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                } else if (std.mem.eql(u8, expr.op, "-")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = sub i32 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                } else if (std.mem.eql(u8, expr.op, "*")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = mul i32 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                } else if (std.mem.eql(u8, expr.op, "/")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = sdiv i32 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                } else {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = icmp ");
                    try g.write(icmpCond(expr.op));
                    try g.write(" i32 ");
                    try g.write(left_val);
                    try g.write(", ");
                    try g.write(right_val);
                    try g.write("\n");
                }
                g.allocator.free(left_val);
                g.allocator.free(right_val);
                return result;
            },
            .unary => {
                const right_val = try g.genLlvmExpr(expr.right.?);
                errdefer g.allocator.free(right_val);
                const result = try g.nextTmp();
                if (std.mem.eql(u8, expr.op, "!")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = icmp eq i32 ");
                    try g.write(right_val);
                    try g.write(", 0\n");
                } else if (std.mem.eql(u8, expr.op, "-")) {
                    try g.write("  ");
                    try g.write(result);
                    try g.write(" = sub i32 0, ");
                    try g.write(right_val);
                    try g.write("\n");
                }
                g.allocator.free(right_val);
                return result;
            },
            else => {
                return try g.allocator.dupe(u8, "0");
            },
        }
    }

    fn genGuardCheck(g: *Generator, guard_stmts: std.ArrayList(ast.Stmt)) !?[]const u8 {
        if (guard_stmts.items.len == 0) return null;
        const stmt = guard_stmts.items[0];
        if (stmt.kind != .expr_stmt) return null;
        const expr = stmt.expr orelse return null;
        return try g.genLlvmExpr(expr);
    }

    fn collectStrings(g: *Generator, prog: ast.Program) !void {
        for (prog.states.items) |st| {
            for (st.actions.items) |act| {
                for (act.body_stmts.items) |stmt| {
                    try g.collectStmtStrings(stmt);
                }
            }
            for (st.transitions.items) |tr| {
                for (tr.body_stmts.items) |stmt| {
                    try g.collectStmtStrings(stmt);
                }
            }
        }
    }

    fn collectStmtStrings(g: *Generator, stmt: ast.Stmt) !void {
        if (stmt.kind == .print) {
            for (stmt.print_args.items) |arg| {
                if (arg.kind == .literal and arg.literal.lit_type == .string) {
                    try g.strings.append(arg.literal.string_val);
                }
            }
        }
        for (stmt.then_body.items) |s| try g.collectStmtStrings(s);
        for (stmt.else_body.items) |s| try g.collectStmtStrings(s);
        for (stmt.stmts.items) |s| try g.collectStmtStrings(s);
    }

    fn emitStringConstants(g: *Generator) !void {
        for (g.strings.items, 0..) |str, idx| {
            try g.write("@.str");
            try std.fmt.format(g.buf.writer(), "{d}", .{idx});
            try g.write(" = private unnamed_addr constant [");
            try std.fmt.format(g.buf.writer(), "{d}", .{str.len + 2});
            try g.write(" x i8] c\"");
            for (str) |c| {
                try g.writeLlvmEscaped(c);
            }
            try g.write("\\0A\\00\"\n");
        }
        if (g.strings.items.len > 0) try g.write("\n");
    }

    fn emitContextType(g: *Generator, prog: ast.Program) !void {
        try g.write("%context_t = type {\n");
        for (prog.context_vars.items) |v| {
            try g.write("    ");
            try g.write(g.mapType(v.var_type));
            try g.write(", ; ");
            try g.write(v.name);
            try g.write("\n");
        }
        for (prog.states.items) |st| {
            for (st.vars.items) |v| {
                try g.write("    ");
                try g.write(g.mapType(v.var_type));
                try g.write(", ; ");
                try g.write(st.name);
                try g.write("_");
                try g.write(v.name);
                try g.write("\n");
            }
        }
        try g.write("    ptr  ; current_state\n");
        try g.write("}\n\n");
    }

    fn genStateFn(g: *Generator, st: ast.StateDecl) !void {
        const fname = try std.mem.concat(g.allocator, u8, &[_][]const u8{ st.name, "_enter" });
        defer g.allocator.free(fname);

        try g.write("define void @");
        try g.write(fname);
        try g.write("(ptr %ctx, i64 %event_id) {\n");
        try g.write("entry:\n");

        const has_enter = for (st.actions.items) |act| {
            if (std.mem.eql(u8, act.action_type, "enter")) break true;
        } else false;

        const has_guarded_transitions = for (st.transitions.items) |tr| {
            if (tr.guard_stmts.items.len > 0) break true;
        } else false;

        // Dispatch on event_id
        if (has_enter) {
            try g.write("  %is_enter = icmp eq i64 %event_id, 0\n");
            if (has_guarded_transitions) {
                try g.write("  br i1 %is_enter, label %enter_body, label %check_guards\n\n");
            } else {
                try g.write("  br i1 %is_enter, label %enter_body, label %done\n\n");
            }
        } else {
            if (has_guarded_transitions) {
                try g.write("  br label %check_guards\n\n");
            } else {
                try g.write("  br label %done\n\n");
            }
        }

        // Enter body
        if (has_enter) {
            try g.write("enter_body:\n");
            for (st.actions.items) |act| {
                if (!std.mem.eql(u8, act.action_type, "enter")) continue;
                for (act.body_stmts.items) |stmt| {
                    try g.genBodyStmt(stmt);
                }
            }
            if (has_guarded_transitions) {
                try g.write("  br label %check_guards\n\n");
            } else {
                try g.write("  ret void\n\n");
            }
        }

        // Guarded transitions — chain with fall-through to done on last
        if (has_guarded_transitions) {
            // Collect guarded transitions
            var guarded = std.ArrayList(*const ast.Transition).init(g.allocator);
            defer guarded.deinit();
            for (st.transitions.items) |*tr| {
                if (tr.guard_stmts.items.len > 0) {
                    try guarded.append(tr);
                }
            }

            var gi: usize = 0;
            var guard_idx: usize = 0;
            try g.write("check_guards:\n");
            while (gi < guarded.items.len) : (gi += 1) {
                const tr = guarded.items[gi];
                const effective_target = if (std.mem.eql(u8, tr.target, "Self")) st.name else tr.target;
                const is_self = std.mem.eql(u8, effective_target, st.name);
                const guard_cond = g.genGuardCheck(tr.guard_stmts) catch null;
                const cond_val = guard_cond orelse {
                    // No expression — unconditional
                    try g.write("  ; unconditional transition to ");
                    try g.write(effective_target);
                    try g.write("\n");
                    if (!is_self) {
                        const sp = try g.nextTmp();
                        try g.write("  ");
                        try g.write(sp);
                        try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
                        try std.fmt.format(g.buf.writer(), "{d}", .{g.contextFieldCount()});
                        try g.write("\n");
                        try g.write("  store ptr @");
                        try g.write(effective_target);
                        try g.write("_enter, ptr ");
                        try g.write(sp);
                        try g.write("\n");
                        try g.write("  call void @");
                        try g.write(effective_target);
                        try g.write("_enter(ptr %ctx, i64 0)\n");
                    }
                    for (tr.body_stmts.items) |body_stmt| {
                        try g.genBodyStmt(body_stmt);
                    }
                    try g.write("  ret void\n\n");
                    continue;
                };

                const fail_label = if (gi + 1 < guarded.items.len) blk: {
                    const label = try std.fmt.allocPrint(g.allocator, "check_guard_next_{d}", .{guard_idx});
                    guard_idx += 1;
                    break :blk label;
                } else "done";

                // Branch prediction hint: guard usually true
                const zext_reg = try g.nextTmp();
                try g.write("  ");
                try g.write(zext_reg);
                try g.write(" = zext i1 ");
                try g.write(cond_val);
                try g.write(" to i64\n");
                const expect_reg = try g.nextTmp();
                try g.write("  ");
                try g.write(expect_reg);
                try g.write(" = call i64 @llvm.expect.i64(i64 ");
                try g.write(zext_reg);
                try g.write(", i64 1)\n");
                const expect_cond_reg = try g.nextTmp();
                try g.write("  ");
                try g.write(expect_cond_reg);
                try g.write(" = icmp ne i64 ");
                try g.write(expect_reg);
                try g.write(", 0\n");
                try g.write("  br i1 ");
                try g.write(expect_cond_reg);
                try g.write(", label %trans_");
                try g.write(effective_target);
                try g.write(", label %");
                try g.write(fail_label);
                try g.write("\n\n");

                try g.write("trans_");
                try g.write(effective_target);
                try g.write(":\n");
                if (!is_self) {
                    const sp = try g.nextTmp();
                    try g.write("  ");
                    try g.write(sp);
                    try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
                    try std.fmt.format(g.buf.writer(), "{d}", .{g.contextFieldCount()});
                    try g.write("\n");
                    try g.write("  store ptr @");
                    try g.write(effective_target);
                    try g.write("_enter, ptr ");
                    try g.write(sp);
                    try g.write("\n");
                }
                for (tr.body_stmts.items) |body_stmt| {
                    try g.genBodyStmt(body_stmt);
                }
                if (!is_self) {
                    try g.write("  call void @");
                    try g.write(effective_target);
                    try g.write("_enter(ptr %ctx, i64 0)\n");
                }
                try g.write("  ret void\n\n");

                g.allocator.free(cond_val);

                if (gi + 1 < guarded.items.len) {
                    try g.write(fail_label);
                    try g.write(":\n");
                }
            }
        }

        try g.write("done:\n");
        try g.write("  ret void\n");
        try g.write("}\n");
    }

    fn genBodyStmt(g: *Generator, stmt: ast.Stmt) !void {
        switch (stmt.kind) {
            .print => {
                if (stmt.print_args.items.len > 0) {
                    const arg0 = stmt.print_args.items[0];
                    if (arg0.kind == .literal and arg0.literal.lit_type == .string) {
                        if (g.globalStringIdx(arg0.literal.string_val)) |idx| {
                            if (stmt.print_args.items.len == 1) {
                                const call_reg = try g.nextTmp();
                                try g.write("  ");
                                try g.write(call_reg);
                                try g.write(" = call i32 @puts(ptr @.str");
                                try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                                try g.write(")\n");
                            } else {
                                // Multi-arg print: parse format string, emit bplus_write for
                                // text segments and bplus_print_i32 for %d specifiers.
                                const fmt = arg0.literal.string_val;
                                var arg_idx: usize = 1;
                                var seg_start: usize = 0;
                                var i: usize = 0;
                                while (i < fmt.len) {
                                    if (fmt[i] == '%') {
                                        if (i + 1 < fmt.len and fmt[i + 1] == 'd') {
                                            if (i > seg_start) {
                                                try g.emitBplusWriteSubstr(idx, seg_start, i - seg_start);
                                            }
                                            const arg = stmt.print_args.items[arg_idx];
                                            arg_idx += 1;
                                            const val = try g.genLlvmExpr(arg);
                                            defer g.allocator.free(val);
                                            try g.write("  call void @bplus_print_i32(i32 ");
                                            try g.write(val);
                                            try g.write(")\n");
                                            i += 2;
                                            seg_start = i;
                                        } else if (i + 1 < fmt.len and fmt[i + 1] == '%') {
                                            if (i > seg_start) {
                                                try g.emitBplusWriteSubstr(idx, seg_start, i - seg_start);
                                            }
                                            try g.emitBplusWriteSubstr(idx, i + 1, 1);
                                            i += 2;
                                            seg_start = i;
                                        } else {
                                            i += 1;
                                        }
                                    } else {
                                        i += 1;
                                    }
                                }
                                if (i > seg_start) {
                                    try g.emitBplusWriteSubstr(idx, seg_start, i - seg_start);
                                }
                            }
                        }
                    }
                }
            },
            .return_stmt => try g.write("  ret void\n"),
            .expr_stmt => {},
            .var_decl => {},
            .assign => {
                const idx = try g.findContextFieldIdx(stmt.assign_name);
                const ptr_reg = try g.nextTmp();
                try g.write("  ");
                try g.write(ptr_reg);
                try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
                try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                try g.write("\n");
                if (stmt.assign_expr) |rhs| {
                    const val_reg = try g.genLlvmExpr(rhs);
                    defer g.allocator.free(val_reg);
                    if (std.mem.eql(u8, stmt.assign_op, "=")) {
                        try g.write("  store i32 ");
                        try g.write(val_reg);
                        try g.write(", ptr ");
                        try g.write(ptr_reg);
                        try g.write("\n");
                    } else if (std.mem.eql(u8, stmt.assign_op, "+=")) {
                        const loaded = try g.nextTmp();
                        try g.write("  ");
                        try g.write(loaded);
                        try g.write(" = load i32, ptr ");
                        try g.write(ptr_reg);
                        try g.write("\n");
                        const added = try g.nextTmp();
                        try g.write("  ");
                        try g.write(added);
                        try g.write(" = add i32 ");
                        try g.write(loaded);
                        try g.write(", ");
                        try g.write(val_reg);
                        try g.write("\n");
                        try g.write("  store i32 ");
                        try g.write(added);
                        try g.write(", ptr ");
                        try g.write(ptr_reg);
                        try g.write("\n");
                    } else if (std.mem.eql(u8, stmt.assign_op, "-=")) {
                        const loaded = try g.nextTmp();
                        try g.write("  ");
                        try g.write(loaded);
                        try g.write(" = load i32, ptr ");
                        try g.write(ptr_reg);
                        try g.write("\n");
                        const subbed = try g.nextTmp();
                        try g.write("  ");
                        try g.write(subbed);
                        try g.write(" = sub i32 ");
                        try g.write(loaded);
                        try g.write(", ");
                        try g.write(val_reg);
                        try g.write("\n");
                        try g.write("  store i32 ");
                        try g.write(subbed);
                        try g.write(", ptr ");
                        try g.write(ptr_reg);
                        try g.write("\n");
                    }
                }
            },
            .if_stmt => {},
            .while_stmt => {},
            .block => {},
            else => {},
        }
    }

    fn genMain(g: *Generator, prog: ast.Program) !void {
        try g.write("define i32 @main() {\n");
        try g.write("entry:\n");
        try g.write("  %ctx = alloca %context_t, align 64\n");

        var idx: usize = 0;
        for (prog.context_vars.items) |v| {
            try g.write("  %f");
            try std.fmt.format(g.buf.writer(), "{d}", .{idx});
            try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
            try std.fmt.format(g.buf.writer(), "{d}", .{idx});
            try g.write("\n");
            if (v.init) |init_expr| {
                try g.write("  store ");
                try g.write(g.mapType(v.var_type));
                try g.write(" ");
                try g.genExpr(init_expr);
                try g.write(", ptr %f");
                try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                try g.write("\n");
            }
            idx += 1;
        }

        for (prog.states.items) |st| {
            for (st.vars.items) |v| {
                try g.write("  %f");
                try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
                try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                try g.write("\n");
                if (v.init) |init_expr| {
                    try g.write("  store ");
                    try g.write(g.mapType(v.var_type));
                    try g.write(" ");
                    try g.genExpr(init_expr);
                    try g.write(", ptr %f");
                    try std.fmt.format(g.buf.writer(), "{d}", .{idx});
                    try g.write("\n");
                }
                idx += 1;
            }
        }

        const sp = try g.nextTmp();
        try g.write("  ");
        try g.write(sp);
        try g.write(" = getelementptr inbounds %context_t, ptr %ctx, i32 0, i32 ");
        try std.fmt.format(g.buf.writer(), "{d}", .{idx});
        try g.write("\n");
        const base = if (prog.start_state.len > 0) prog.start_state
            else if (prog.states.items.len > 0) prog.states.items[0].name
            else "_start";
        try g.write("  store ptr @");
        try g.write(base);
        try g.write("_enter, ptr ");
        try g.write(sp);
        try g.write("\n");
        // Prefetch initial state function code
        const init_fn = try g.nextTmp();
        try g.write("  ");
        try g.write(init_fn);
        try g.write(" = load ptr, ptr ");
        try g.write(sp);
        try g.write("\n");
        try g.write("  call void @llvm.prefetch(ptr ");
        try g.write(init_fn);
        try g.write(", i32 0, i32 3, i32 1)\n");
        // Prefetch context (first cache line)
        try g.write("  call void @llvm.prefetch(ptr %ctx, i32 0, i32 3, i32 1)\n");
        try g.write("  call void @");
        try g.write(base);
        try g.write("_enter(ptr %ctx, i64 0)\n");
        try g.write("  ret i32 0\n");
        try g.write("}\n");
    }

    fn globalStringIdx(g: *Generator, needle: []const u8) ?usize {
        for (g.strings.items, 0..) |s, i| {
            if (std.mem.eql(u8, s, needle)) return i;
        }
        return null;
    }

    /// Emits: gep @.str{idx}, i64 {offset}  then  call @bplus_write(ptr, i32 {len})
    fn emitBplusWriteSubstr(g: *Generator, str_idx: usize, offset: usize, len: usize) !void {
        const gep_reg = try g.nextTmp();
        try g.write("  ");
        try g.write(gep_reg);
        try g.write(" = getelementptr i8, ptr @.str");
        try std.fmt.format(g.buf.writer(), "{d}", .{str_idx});
        try g.write(", i64 ");
        try std.fmt.format(g.buf.writer(), "{d}", .{offset});
        try g.write("\n");
        try g.write("  call void @bplus_write(ptr ");
        try g.write(gep_reg);
        try g.write(", i32 ");
        try std.fmt.format(g.buf.writer(), "{d}", .{len});
        try g.write(")\n");
        g.allocator.free(gep_reg);
    }

    fn countContextFields(_: *Generator, prog: ast.Program) usize {
        var count: usize = prog.context_vars.items.len;
        for (prog.states.items) |st| {
            count += st.vars.items.len;
        }
        return count;
    }

    fn contextFieldCount(g: *Generator) usize {
        return g.context_fields;
    }

    fn mapType(_: *Generator, t: []const u8) []const u8 {
        if (std.mem.eql(u8, t, "int")) return "i32";
        if (std.mem.eql(u8, t, "uint")) return "i32";
        if (std.mem.eql(u8, t, "float")) return "float";
        if (std.mem.eql(u8, t, "double")) return "double";
        if (std.mem.eql(u8, t, "bool")) return "i8";
        if (std.mem.eql(u8, t, "byte")) return "i8";
        if (std.mem.eql(u8, t, "string")) return "ptr";
        if (std.mem.eql(u8, t, "void")) return "void";
        if (std.mem.eql(u8, t, "inferred")) return "i32";
        return t;
    }

    fn genExpr(g: *Generator, expr: *ast.Expr) !void {
        switch (expr.kind) {
            .literal => {
                switch (expr.literal.lit_type) {
                    .int => try std.fmt.format(g.buf.writer(), "{d}", .{expr.literal.int_val}),
                    .float => try std.fmt.format(g.buf.writer(), "{d}", .{expr.literal.float_val}),
                    .string => {
                        try g.write("\"");
                        try g.write(expr.literal.string_val);
                        try g.write("\"");
                    },
                    .boolean => {
                        if (expr.literal.bool_val) { try g.write("true"); } else { try g.write("false"); }
                    },
                }
            },
            .ident => try g.write(expr.ident),
            .binary => {
                if (expr.left == null or expr.right == null) return;
                try g.genExpr(expr.left.?);
                try g.write(" ");
                try g.write(expr.op);
                try g.write(" ");
                try g.genExpr(expr.right.?);
            },
            .unary => {
                try g.write(expr.op);
                if (expr.right) |r| try g.genExpr(r);
            },
            .call => {
                try g.write(expr.callee);
                try g.write("(");
                for (expr.args.items, 0..) |arg, i| {
                    if (i > 0) try g.write(", ");
                    try g.genExpr(arg);
                }
                try g.write(")");
            },
            else => {},
        }
    }

    fn write(g: *Generator, s: []const u8) !void {
        try g.buf.appendSlice(s);
    }

    fn writeLlvmEscaped(g: *Generator, c: u8) !void {
        switch (c) {
            '\\' => try g.write("\\5C"),
            '"' => try g.write("\\22"),
            '\n' => try g.write("\\0A"),
            '\r' => try g.write("\\0D"),
            '\t' => try g.write("\\09"),
            else => {
                if (c >= 32 and c < 127) {
                    try g.buf.append(c);
                } else {
                    try g.write("\\");
                    try std.fmt.format(g.buf.writer(), "{X:0>2}", .{c});
                }
            },
        }
    }
};
